"""create_initial_domain_tables

Revision ID: c5ae6d5f5564
Revises: 
Create Date: 2026-09-14 12:53:02.926926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ae6d5f5564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('earliest_start', sa.DateTime(), nullable=False),
    sa.Column('latest_end', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['track_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_section_id'), ['section_id'], unique=False)

    op.create_table('section_adjacencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('section_a_id', sa.String(), nullable=False),
    sa.Column('section_b_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['section_a_id'], ['track_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_b_id'], ['track_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_a_id', 'section_b_id', name='uq_section_adjacency')
    )
    with op.batch_alter_table('section_adjacencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_adjacencies_section_a_id'), ['section_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_adjacencies_section_b_id'), ['section_b_id'], unique=False)

    op.create_table('scheduled_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['track_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_blocks_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_blocks_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_blocks_task_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_blocks_section_id'))

    op.drop_table('scheduled_blocks')
    with op.batch_alter_table('section_adjacencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_adjacencies_section_b_id'))
        batch_op.drop_index(batch_op.f('ix_section_adjacencies_section_a_id'))

    op.drop_table('section_adjacencies')
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_section_id'))

    op.drop_table('maintenance_tasks')
    op.drop_table('train_slots')
    op.drop_table('track_sections')
    # ### end Alembic commands ###
